version: '3.8'

services:
  corner-fe:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
      - .env:/.env:ro
    environment:
      - CHOKIDAR_USEPOLLING=true # hot reload용 설정
    command: npm run dev -- --host 0.0.0.0
    networks:
      - corner-net

networks:
  corner-net:
    external: true
