name: ci/cd corner2025-fe

on:
  push:
    branches:
      - "main"

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Upload image to server via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_NAME }}
          password: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: .
          target: "/corner2025/cornerFE/"

      - name: Run remote deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_NAME }}
          password: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -ex

            cd /corner2025/cornerFE

            # env만들기
            touch .env
            echo "VITE_SERVER_URL=${{ secrets.VITE_SERVER_URL }}" > .env
            echo "VITE_KAKAO_MAP_API_KEY=${{ secrets.VITE_KAKAO_MAP_API_KEY }}" >> .env

            chmod 600 .env
            
            docker-compose down || true
            docker system prune -a  # 쓸데없는거 지우기 ㅎㅎ
            docker-compose build --no-cache
            docker-compose up -d --force-recreate
